# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'Alomafire_codeExample' do


  # Pods for Alomafire_codeExample


pod 'Alamofire', '~> 5.5'


end
